services:
  db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    shm_size: 128mb
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DBNAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: